gcc -std=gnu11 -Wall -Wextra -Werror -O3 -o wav2pcm16k wav2pcm16k.c \
    \
    -Wno-expansion-to-defined \
    -Wno-format-truncation \
    -Wno-implicit-fallthrough \
    \
    -Iaudio-downsampler \
    audio-downsampler/decimate.c \
    \
    -Ilibsndfile/src/ \
    libsndfile/src/aiff.c \
    libsndfile/src/alac.c \
    libsndfile/src/alaw.c \
    libsndfile/src/au.c \
    libsndfile/src/audio_detect.c \
    libsndfile/src/avr.c \
    libsndfile/src/broadcast.c \
    libsndfile/src/caf.c \
    libsndfile/src/cart.c \
    libsndfile/src/chanmap.c \
    libsndfile/src/chunk.c \
    libsndfile/src/command.c \
    libsndfile/src/common.c \
    libsndfile/src/dither.c \
    libsndfile/src/double64.c \
    libsndfile/src/dwd.c \
    libsndfile/src/dwvw.c \
    libsndfile/src/file_io.c \
    libsndfile/src/flac.c \
    libsndfile/src/float32.c \
    libsndfile/src/g72x.c \
    libsndfile/src/gsm610.c \
    libsndfile/src/htk.c \
    libsndfile/src/id3.c \
    libsndfile/src/ima_adpcm.c \
    libsndfile/src/ima_oki_adpcm.c \
    libsndfile/src/interleave.c \
    libsndfile/src/ircam.c \
    libsndfile/src/macos.c \
    libsndfile/src/mat4.c \
    libsndfile/src/mat5.c \
    libsndfile/src/mpc2k.c \
    libsndfile/src/ms_adpcm.c \
    libsndfile/src/new.c \
    libsndfile/src/nist.c \
    libsndfile/src/ogg.c \
    libsndfile/src/ogg_opus.c \
    libsndfile/src/ogg_pcm.c \
    libsndfile/src/ogg_speex.c \
    libsndfile/src/ogg_vorbis.c \
    libsndfile/src/paf.c \
    libsndfile/src/pcm.c \
    libsndfile/src/pvf.c \
    libsndfile/src/raw.c \
    libsndfile/src/rf64.c \
    libsndfile/src/rx2.c \
    libsndfile/src/sd2.c \
    libsndfile/src/sds.c \
    libsndfile/src/sndfile.c \
    libsndfile/src/strings.c \
    libsndfile/src/svx.c \
    libsndfile/src/txw.c \
    libsndfile/src/ulaw.c \
    libsndfile/src/voc.c \
    libsndfile/src/vox_adpcm.c \
    libsndfile/src/w64.c \
    libsndfile/src/wav.c \
    libsndfile/src/wavlike.c \
    libsndfile/src/windows.c \
    libsndfile/src/wve.c \
    libsndfile/src/xi.c \
    \
    -Ilibsndfile/src/ALAC/ \
    libsndfile/src/ALAC/ag_dec.c \
    libsndfile/src/ALAC/ag_enc.c \
    libsndfile/src/ALAC/ALACBitUtilities.c \
    libsndfile/src/ALAC/alac_decoder.c \
    libsndfile/src/ALAC/alac_encoder.c \
    libsndfile/src/ALAC/dp_dec.c \
    libsndfile/src/ALAC/dp_enc.c \
    libsndfile/src/ALAC/matrix_dec.c \
    libsndfile/src/ALAC/matrix_enc.c \
    \
    -Ilibsndfile/src/G72x/ \
    libsndfile/src/G72x/g721.c \
    libsndfile/src/G72x/g723_16.c \
    libsndfile/src/G72x/g723_24.c \
    libsndfile/src/G72x/g723_40.c \
    libsndfile/src/G72x/g72x.c \
    \
    -Ilibsndfile/src/GSM610/ \
    libsndfile/src/GSM610/add.c \
    libsndfile/src/GSM610/code.c \
    libsndfile/src/GSM610/decode.c \
    libsndfile/src/GSM610/gsm_create.c \
    libsndfile/src/GSM610/gsm_decode.c \
    libsndfile/src/GSM610/gsm_destroy.c \
    libsndfile/src/GSM610/gsm_encode.c \
    libsndfile/src/GSM610/gsm_option.c \
    libsndfile/src/GSM610/long_term.c \
    libsndfile/src/GSM610/lpc.c \
    libsndfile/src/GSM610/preprocess.c \
    libsndfile/src/GSM610/rpe.c \
    libsndfile/src/GSM610/short_term.c \
    libsndfile/src/GSM610/table.c \
    \
    -lm

gcc -std=gnu11 -Wall -Wextra -Werror -O3 -o wav2pcm48k wav2pcm48k.c \
    \
    -Wno-expansion-to-defined \
    -Wno-format-truncation \
    -Wno-implicit-fallthrough \
    \
    -Iaudio-downsampler \
    audio-downsampler/decimate.c \
    \
    -Ilibsndfile/src/ \
    libsndfile/src/aiff.c \
    libsndfile/src/alac.c \
    libsndfile/src/alaw.c \
    libsndfile/src/au.c \
    libsndfile/src/audio_detect.c \
    libsndfile/src/avr.c \
    libsndfile/src/broadcast.c \
    libsndfile/src/caf.c \
    libsndfile/src/cart.c \
    libsndfile/src/chanmap.c \
    libsndfile/src/chunk.c \
    libsndfile/src/command.c \
    libsndfile/src/common.c \
    libsndfile/src/dither.c \
    libsndfile/src/double64.c \
    libsndfile/src/dwd.c \
    libsndfile/src/dwvw.c \
    libsndfile/src/file_io.c \
    libsndfile/src/flac.c \
    libsndfile/src/float32.c \
    libsndfile/src/g72x.c \
    libsndfile/src/gsm610.c \
    libsndfile/src/htk.c \
    libsndfile/src/id3.c \
    libsndfile/src/ima_adpcm.c \
    libsndfile/src/ima_oki_adpcm.c \
    libsndfile/src/interleave.c \
    libsndfile/src/ircam.c \
    libsndfile/src/macos.c \
    libsndfile/src/mat4.c \
    libsndfile/src/mat5.c \
    libsndfile/src/mpc2k.c \
    libsndfile/src/ms_adpcm.c \
    libsndfile/src/new.c \
    libsndfile/src/nist.c \
    libsndfile/src/ogg.c \
    libsndfile/src/ogg_opus.c \
    libsndfile/src/ogg_pcm.c \
    libsndfile/src/ogg_speex.c \
    libsndfile/src/ogg_vorbis.c \
    libsndfile/src/paf.c \
    libsndfile/src/pcm.c \
    libsndfile/src/pvf.c \
    libsndfile/src/raw.c \
    libsndfile/src/rf64.c \
    libsndfile/src/rx2.c \
    libsndfile/src/sd2.c \
    libsndfile/src/sds.c \
    libsndfile/src/sndfile.c \
    libsndfile/src/strings.c \
    libsndfile/src/svx.c \
    libsndfile/src/txw.c \
    libsndfile/src/ulaw.c \
    libsndfile/src/voc.c \
    libsndfile/src/vox_adpcm.c \
    libsndfile/src/w64.c \
    libsndfile/src/wav.c \
    libsndfile/src/wavlike.c \
    libsndfile/src/windows.c \
    libsndfile/src/wve.c \
    libsndfile/src/xi.c \
    \
    -Ilibsndfile/src/ALAC/ \
    libsndfile/src/ALAC/ag_dec.c \
    libsndfile/src/ALAC/ag_enc.c \
    libsndfile/src/ALAC/ALACBitUtilities.c \
    libsndfile/src/ALAC/alac_decoder.c \
    libsndfile/src/ALAC/alac_encoder.c \
    libsndfile/src/ALAC/dp_dec.c \
    libsndfile/src/ALAC/dp_enc.c \
    libsndfile/src/ALAC/matrix_dec.c \
    libsndfile/src/ALAC/matrix_enc.c \
    \
    -Ilibsndfile/src/G72x/ \
    libsndfile/src/G72x/g721.c \
    libsndfile/src/G72x/g723_16.c \
    libsndfile/src/G72x/g723_24.c \
    libsndfile/src/G72x/g723_40.c \
    libsndfile/src/G72x/g72x.c \
    \
    -Ilibsndfile/src/GSM610/ \
    libsndfile/src/GSM610/add.c \
    libsndfile/src/GSM610/code.c \
    libsndfile/src/GSM610/decode.c \
    libsndfile/src/GSM610/gsm_create.c \
    libsndfile/src/GSM610/gsm_decode.c \
    libsndfile/src/GSM610/gsm_destroy.c \
    libsndfile/src/GSM610/gsm_encode.c \
    libsndfile/src/GSM610/gsm_option.c \
    libsndfile/src/GSM610/long_term.c \
    libsndfile/src/GSM610/lpc.c \
    libsndfile/src/GSM610/preprocess.c \
    libsndfile/src/GSM610/rpe.c \
    libsndfile/src/GSM610/short_term.c \
    libsndfile/src/GSM610/table.c \
    \
    -lm
