set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)
set(CMAKE_C_COMPILER arm-fsl-linux-gnueabi-gcc)
set(CMAKE_C_FLAGS_INIT "-ffast-math -mfpu=neon -mfloat-abi=softfp")
set(BUILD_TARGET gtlt)
